//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sazmanyar.GoogleMapOffline.Resources.Sazmanyar.GoogleMapOffline {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sazmanyar.GoogleMapOffline.Resources.Sazmanyar.GoogleMapOffline.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info Window Anchor X.
        /// </summary>
        internal static string _Settings_InfoWindowAnchor_X {
            get {
                return ResourceManager.GetString("_Settings_InfoWindowAnchor_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info Window Anchor Y.
        /// </summary>
        internal static string _Settings_InfoWindowAnchor_Y {
            get {
                return ResourceManager.GetString("_Settings_InfoWindowAnchor_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marker Anchor Icon X.
        /// </summary>
        internal static string _Settings_MarkerAnchorIcon_X {
            get {
                return ResourceManager.GetString("_Settings_MarkerAnchorIcon_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marker Anchor Icon Y.
        /// </summary>
        internal static string _Settings_MarkerAnchorIcon_Y {
            get {
                return ResourceManager.GetString("_Settings_MarkerAnchorIcon_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marker Icon X.
        /// </summary>
        internal static string _Settings_MarkerIcon_X {
            get {
                return ResourceManager.GetString("_Settings_MarkerIcon_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marker Icon Y.
        /// </summary>
        internal static string _Settings_MarkerIcon_Y {
            get {
                return ResourceManager.GetString("_Settings_MarkerIcon_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marker Shadow Icon X.
        /// </summary>
        internal static string _Settings_MarkerShadowIcon_X {
            get {
                return ResourceManager.GetString("_Settings_MarkerShadowIcon_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marker Shadow Icon Y.
        /// </summary>
        internal static string _Settings_MarkerShadowIcon_Y {
            get {
                return ResourceManager.GetString("_Settings_MarkerShadowIcon_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GoogleMapOffline.
        /// </summary>
        internal static string _SettingsActionDescription_LabelText {
            get {
                return ResourceManager.GetString("_SettingsActionDescription_LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GoogleMapOffline.
        /// </summary>
        internal static string _SettingsActionTitle_LabelText {
            get {
                return ResourceManager.GetString("_SettingsActionTitle_LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس لود مربوط به کنترل صفحه.
        /// </summary>
        internal static string _SettingsAdress_ascxPath {
            get {
                return ResourceManager.GetString("_SettingsAdress_ascxPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تخصیص آدرس تصاویر .
        /// </summary>
        internal static string _SettingsAdress_Of_Image_Location {
            get {
                return ResourceManager.GetString("_SettingsAdress_Of_Image_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس وب مربوط به سایت لیست مورد نظر را تعیین کنید(برای اشاره به سایت خالی از / استفاده کنید)ه.
        /// </summary>
        internal static string _SettingsBaseWebUrlInfo {
            get {
                return ResourceManager.GetString("_SettingsBaseWebUrlInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعیین ستون اول جهت جستجو انتخابی در لیست می باشد(chb مقدار خالی به منزلهء عدم نمایش می باشد).
        /// </summary>
        internal static string _SettingsCheckList_by_column1 {
            get {
                return ResourceManager.GetString("_SettingsCheckList_by_column1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعیین ستون دوم جهت جستجو انتخابی در لیست می باشد(chb مقدار خالی به منزلهء عدم نمایش می باشد).
        /// </summary>
        internal static string _SettingsCheckList_by_column2 {
            get {
                return ResourceManager.GetString("_SettingsCheckList_by_column2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعیین ستون سوم جهت جستجو انتخابی در لیست می باشد(chb مقدار خالی به منزلهء عدم نمایش می باشد).
        /// </summary>
        internal static string _SettingsCheckList_by_column3 {
            get {
                return ResourceManager.GetString("_SettingsCheckList_by_column3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان استفاده از قابلیت درگ و دراپت.
        /// </summary>
        internal static string _Settingsdraggable {
            get {
                return ResourceManager.GetString("_Settingsdraggable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان استفاده از اسکرول موس.
        /// </summary>
        internal static string _SettingsenableScrollWheelZoom {
            get {
                return ResourceManager.GetString("_SettingsenableScrollWheelZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعیین ستون جهت دسته بندی.
        /// </summary>
        internal static string _Settingsfilterd_by_column {
            get {
                return ResourceManager.GetString("_Settingsfilterd_by_column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعیین ستون اول جهت جستجو موردی در لیست می باشد(cmb مقدار خالی به منزلهء عدم نمایش می باشد).
        /// </summary>
        internal static string _Settingsfilterd_by_column1 {
            get {
                return ResourceManager.GetString("_Settingsfilterd_by_column1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعیین ستون دوم جهت جستجو موردی در لیست می باشد(cmb مقدار خالی به منزلهء عدم نمایش می باشد).
        /// </summary>
        internal static string _Settingsfilterd_by_column2 {
            get {
                return ResourceManager.GetString("_Settingsfilterd_by_column2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعیین ستون سوم جهت جستجو موردی در لیست می باشد(cmb مقدار خالی به منزلهء عدم نمایش می باشد).
        /// </summary>
        internal static string _Settingsfilterd_by_column3 {
            get {
                return ResourceManager.GetString("_Settingsfilterd_by_column3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات فیلتر در کوئری استرینگ.
        /// </summary>
        internal static string _SettingsFiltered_In_QueryString {
            get {
                return ResourceManager.GetString("_SettingsFiltered_In_QueryString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام ستون امکان نمایش در مرکز در لیست می باشد.
        /// </summary>
        internal static string _SettingsIsCenField {
            get {
                return ResourceManager.GetString("_SettingsIsCenField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا Joinاز نوع OuterJoin است؟.
        /// </summary>
        internal static string _SettingsIsOuterJoin {
            get {
                return ResourceManager.GetString("_SettingsIsOuterJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس جاوا اسکریپت مربوط به نمایش جزئیات در جستجو.
        /// </summary>
        internal static string _SettingsJSDrowDetailInfoAddressUrl {
            get {
                return ResourceManager.GetString("_SettingsJSDrowDetailInfoAddressUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس فایل جاوا اسکریپت رسم شکلک(DrowMarker.js).
        /// </summary>
        internal static string _SettingsJSDrowMarkerAddressUrl {
            get {
                return ResourceManager.GetString("_SettingsJSDrowMarkerAddressUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام ستون Latitude در لیست می باشد.
        /// </summary>
        internal static string _SettingsLatField {
            get {
                return ResourceManager.GetString("_SettingsLatField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام لیست اطلاعات نقشه می باشد.
        /// </summary>
        internal static string _SettingsListName {
            get {
                return ResourceManager.GetString("_SettingsListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First List Helper Url.
        /// </summary>
        internal static string _SettingsListUrlHelper1 {
            get {
                return ResourceManager.GetString("_SettingsListUrlHelper1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second List Helper Url.
        /// </summary>
        internal static string _SettingsListUrlHelper2 {
            get {
                return ResourceManager.GetString("_SettingsListUrlHelper2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third List Helper Url.
        /// </summary>
        internal static string _SettingsListUrlHelper3 {
            get {
                return ResourceManager.GetString("_SettingsListUrlHelper3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forth List Helper Url.
        /// </summary>
        internal static string _SettingsListUrlHelper4 {
            get {
                return ResourceManager.GetString("_SettingsListUrlHelper4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fifth List Helper Url.
        /// </summary>
        internal static string _SettingsListUrlHelper5 {
            get {
                return ResourceManager.GetString("_SettingsListUrlHelper5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام ستون Longitude در لیست می باشد.
        /// </summary>
        internal static string _SettingsLongField {
            get {
                return ResourceManager.GetString("_SettingsLongField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تخصیص سطح بلای زون.
        /// </summary>
        internal static string _SettingsmaxinumLevel {
            get {
                return ResourceManager.GetString("_SettingsmaxinumLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداکثر تعداد نتایج جستجو.
        /// </summary>
        internal static string _SettingsMaxSearchResult {
            get {
                return ResourceManager.GetString("_SettingsMaxSearchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تخصیص سطح پایین زون.
        /// </summary>
        internal static string _SettingsmininumLevel {
            get {
                return ResourceManager.GetString("_SettingsmininumLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان استفاده از ابزار پیمایش.
        /// </summary>
        internal static string _SettingsnavigationControl {
            get {
                return ResourceManager.GetString("_SettingsnavigationControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام ستون مشترک بین لیست ها (InternalColumnName) و ویو مورد نظر.
        /// </summary>
        internal static string _SettingsRelationalColumnBetweenListsAndViews {
            get {
                return ResourceManager.GetString("_SettingsRelationalColumnBetweenListsAndViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام ستون های تفکیک شده با کاما برای لود در Mapapoint.
        /// </summary>
        internal static string _SettingsRelationalColumnForloadInMapPoint {
            get {
                return ResourceManager.GetString("_SettingsRelationalColumnForloadInMapPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان استفاده از مقیاس در نقشه.
        /// </summary>
        internal static string _SettingsscaleControl {
            get {
                return ResourceManager.GetString("_SettingsscaleControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعیین ستون اول جهت جستجو متنی در لیست می باشد(txt مقدار خالی به منزلهء عدم نمایش می باشد).
        /// </summary>
        internal static string _SettingsSearched_by_column1 {
            get {
                return ResourceManager.GetString("_SettingsSearched_by_column1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعیین ستون دوم جهت جستجو متنی در لیست می باشد(txt مقدار خالی به منزلهء عدم نمایش می باشد).
        /// </summary>
        internal static string _SettingsSearched_by_column2 {
            get {
                return ResourceManager.GetString("_SettingsSearched_by_column2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعیین ستون سوم جهت جستجو متنی در لیست می باشد(txt مقدار خالی به منزلهء عدم نمایش می باشد).
        /// </summary>
        internal static string _SettingsSearched_by_column3 {
            get {
                return ResourceManager.GetString("_SettingsSearched_by_column3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلد اول جهت نمایش در نتایج جستجو.
        /// </summary>
        internal static string _SettingsSearchResultField1 {
            get {
                return ResourceManager.GetString("_SettingsSearchResultField1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلد دوم جهت نمایش در نتایج جستجو.
        /// </summary>
        internal static string _SettingsSearchResultField2 {
            get {
                return ResourceManager.GetString("_SettingsSearchResultField2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعیین آدرس برای حذف از لینک ها.
        /// </summary>
        internal static string _SettingsShouldRemovedFromBaseUrl {
            get {
                return ResourceManager.GetString("_SettingsShouldRemovedFromBaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا باید همهء مارکرهای موجود برای اولین بار نشان داده شوند؟.
        /// </summary>
        internal static string _SettingsShowAllMarkerForFirstTime {
            get {
                return ResourceManager.GetString("_SettingsShowAllMarkerForFirstTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا باید همهء مارکرهای موجود برای اولین بار نشان داده شوند؟.
        /// </summary>
        internal static string _SettingsShowAllMarkerForFirstTime1 {
            get {
                return ResourceManager.GetString("_SettingsShowAllMarkerForFirstTime1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان نمایش با دسترسی مدیر سایت.
        /// </summary>
        internal static string _SettingsShowByAdminPrevilage {
            get {
                return ResourceManager.GetString("_SettingsShowByAdminPrevilage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش ContextMenu .
        /// </summary>
        internal static string _SettingsShowContextMenu {
            get {
                return ResourceManager.GetString("_SettingsShowContextMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا پنل جستجو نشان داده شود؟.
        /// </summary>
        internal static string _SettingsShowSearchPanel {
            get {
                return ResourceManager.GetString("_SettingsShowSearchPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متن ارتباط با بانک - Connection String - در صورت عدم وجود مقدار اطلاعات با سطح دسترسی کاربر جاری به صورت اتوماتیک از بانک واکشی می شود.
        /// </summary>
        internal static string _SettingsSqlQueryConnectionString {
            get {
                return ResourceManager.GetString("_SettingsSqlQueryConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کوئری موجود در بانک اطلاعاتی.
        /// </summary>
        internal static string _SettingsSqlQueryViewName {
            get {
                return ResourceManager.GetString("_SettingsSqlQueryViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام ستون وضعیت در لیست می باشد.
        /// </summary>
        internal static string _SettingsStateField {
            get {
                return ResourceManager.GetString("_SettingsStateField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام ستون عنوان در لیست می باشد.
        /// </summary>
        internal static string _SettingsTitleField {
            get {
                return ResourceManager.GetString("_SettingsTitleField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استفاده از ورژن جدید.
        /// </summary>
        internal static string _SettingsUseNewVersion {
            get {
                return ResourceManager.GetString("_SettingsUseNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ناو ویو مربوط به لیست می باشد.
        /// </summary>
        internal static string _SettingsView_name {
            get {
                return ResourceManager.GetString("_SettingsView_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام ویو مربوط به لیست.
        /// </summary>
        internal static string _SettingsView_nameField {
            get {
                return ResourceManager.GetString("_SettingsView_nameField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تخصیص زون پیشفرض.
        /// </summary>
        internal static string _SettingsZoomLevel {
            get {
                return ResourceManager.GetString("_SettingsZoomLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GoogleMapOfflineWebpart Description.
        /// </summary>
        internal static string _WebpartDescription {
            get {
                return ResourceManager.GetString("_WebpartDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GoogleMapOffline.
        /// </summary>
        internal static string _WebpartTitle {
            get {
                return ResourceManager.GetString("_WebpartTitle", resourceCulture);
            }
        }
    }
}
